# Generated by Django 3.2.14 on 2022-07-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.order')),
            ],
            options={
                'db_table': 'order_line_item',
                'ordering': ('-created_at',),
                'unique_together': {('order_id', 'book_id')},
            },
        ),
    ]
